---
security_ssh_port: 2859
unnecessary_services:
  - postfix
  - telnet

unnecessary_software:
  - tcpdump
  - nmap
  - ncat
  - wpa_supplicant
  - rsh-server
  - telnet-server
  - nano
  - sendmail

  - xserver-xorg-core
