---
- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: dist

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the Debian or Ubuntu server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
  register: rebooted

- debug:
    msg: "Server is back up and running"
  when: rebooted is changed
