version: '3.8'

services:
  reverse-proxy:
    image: caddy:2.7.4-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

# ---------------------------------------------------

  it-tools:
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    container_name: it-tools


# ----------------------------------------------------

volumes:
  caddy_data:
  caddy_config:
