---
- name: Ensure /etc/containers exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ container_dir }}"
    - "{{ compose_dir }}"

- name: Ensure necessary software is installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - software-properties-common
    - iptables
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - python3
    - python3-pip

- name: Installing podman
  apt:
    name: podman
    state: present

- name: Install podman-compose
  ansible.builtin.pip:
    name: podman-compose

- name: Start and enable the podman service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: podman.socket

