---
- hosts: marvin
  gather_facts: true
  become: true
  roles:
    - { role: ubuntu_setup, tags: ['setup'] }
    - { role: ubuntu_maintenance, tags: ['setup'] }
    - { role: docker, tags: ['setup'] }
    - { role: web_server, tags: ['setup'] }

  tasks:
    - name: Make sure project folders exists
      ansible.builtin.file:
        path: "{{ projects_dir }}/{{ item }}"
        state: directory
        owner: "{{ server_admin_user }}"
        group: "{{ server_admin_user }}"
        mode: "0755"
      loop:
        - "{{ plausible_project_dir }}"

    - name: Ensure secrets folder exists
      become: true
      ansible.builtin.file:
        path: "/run/secrets/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - "{{ plausible_project_dir }}"

    - name: Write secrets files for plausible
      become: true
      no_log: true
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "/run/secrets/{{ plausible_project_dir }}/{{ item.key }}"
        mode: "0600"
      loop: "{{ plausible_secret_variables | dict2items }}"

    - name: Write the Caddyfile
      template:
        src: "templates/marvin/Caddyfile.j2"
        dest: "{{ projects_dir }}/{{ plausible_project_dir }}/Caddyfile"

    - name: Write the docker compose file
      ansible.builtin.template:
        src: "templates/marvin/docker-compose.yml.j2"
        dest: "{{ projects_dir }}/{{ plausible_project_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Build and deploy plausible
      community.docker.docker_compose_v2:
        project_src: "{{ projects_dir }}/{{ plausible_project_dir }}"
        state: present
        pull: always
        build: always
        recreate: always
        remove_orphans: true

    - name: Remove dangling Docker images
      community.docker.docker_prune:
        images: true
        networks: true
        builder_cache: true

