---
- name: Ensure /etc/containers exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ container_dir }}"
    - "{{ compose_dir }}"

- name: Ensure necessary software is installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - software-properties-common
    - iptables
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - python3
    - python3-pip

- name: Installing podman
  apt:
    name: podman
    state: present

- name: Install podman-compose
  ansible.builtin.pip:
    name: podman-compose

- name: Start and enable the podman service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: podman.socket

# Getting 'Error validating CNI config file - plugin does not support config version "1.0.0"' Seems to be because the podman version on Ubuntu is OLD and nothing much is being done about it. 2023.09.27 - Check the version later, and see if the task can be deleted
- name: Attempt at fixing a podman issue with Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/cni/net.d/compose_default.conflist
    regexp: '"cniVersion": "1.0.0"'
    line: '   "cniVersion": "0.4.0"'
# Well that didn't work, maybe I should just give up and run Docker...
